// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ALUvN1PnzWW4j2UHtzbo8-1B4QLOg1Q',
    appId: '1:492249576098:web:21b2e3cbf2042089631dfb',
    messagingSenderId: '492249576098',
    projectId: 'history-app-dev-fce4a',
    authDomain: 'history-app-dev-fce4a.firebaseapp.com',
    storageBucket: 'history-app-dev-fce4a.firebasestorage.app',
    measurementId: 'G-4J7HKN2BTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMUaVq37kdBcMrVXjK7865WMWXbL2u9k',
    appId: '1:492249576098:android:f8dc64884ee5a22d631dfb',
    messagingSenderId: '492249576098',
    projectId: 'history-app-dev-fce4a',
    storageBucket: 'history-app-dev-fce4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Rbmr8eU94qcn6gFqgujbDqLoLv28kIU',
    appId: '1:492249576098:ios:030b476d4a153556631dfb',
    messagingSenderId: '492249576098',
    projectId: 'history-app-dev-fce4a',
    storageBucket: 'history-app-dev-fce4a.firebasestorage.app',
    iosBundleId: 'com.example.japaneseHistoryApp',
  );
}
