// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8VKPOi8boYOHWtK5HTRKixh3NVtCxxXE',
    appId: '1:121798228921:web:730e12da039fcdf4511468',
    messagingSenderId: '121798228921',
    projectId: 'history-app-fa0c5',
    authDomain: 'history-app-fa0c5.firebaseapp.com',
    storageBucket: 'history-app-fa0c5.firebasestorage.app',
    measurementId: 'G-H3WR0CGEY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1LIvXuJ3P3KGINf1jn3GzwE-X0m8ka9A',
    appId: '1:121798228921:android:9227b5ddef861d7c511468',
    messagingSenderId: '121798228921',
    projectId: 'history-app-fa0c5',
    storageBucket: 'history-app-fa0c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvuvqARXW91mAoxszv2HXGEpwUFpCayg4',
    appId: '1:121798228921:ios:95e37205b9edaa1e511468',
    messagingSenderId: '121798228921',
    projectId: 'history-app-fa0c5',
    storageBucket: 'history-app-fa0c5.firebasestorage.app',
    iosBundleId: 'com.example.japaneseHistoryApp',
  );
}
